# Generated by Django 2.1.7 on 2019-04-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0008_dondeestamos_quehacemos_quienessomos_transparencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alianzas',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': "'Donde Estamos'",
                'verbose_name_plural': "'Donde Estamos'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': "'App'",
                'verbose_name_plural': "'App'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AyudaDifundiendo',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': "'Ayuda Difundiendo'",
                'verbose_name_plural': "'Ayuda Difundiendo'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': "'Carrera'",
                'verbose_name_plural': "'Carrera'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ComoColaborar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': "'DondeEstamos'",
                'verbose_name_plural': "'DondeEstamos'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Legado',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': "'Legado'",
                'verbose_name_plural': "'Legado'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QuieroDonar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': "'QuieroDonar'",
                'verbose_name_plural': "'QuieroDonar'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='quehacemos',
            options={'verbose_name': "'Que Hacemos'", 'verbose_name_plural': "'Que Hacemos'"},
        ),
    ]
