# Generated by Django 2.1.7 on 2019-04-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0009_auto_20190410_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('nombre_sponsor', models.CharField(help_text='Overwrites the default title', max_length=100, verbose_name='Empresa')),
                ('url_sponsor', models.URLField(blank=True, null=True)),
                ('imagen_sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='alianzas',
            options={'verbose_name': "'Alianzas'", 'verbose_name_plural': "'Alianzas'"},
        ),
        migrations.AlterModelOptions(
            name='comocolaborar',
            options={'verbose_name': "'Como Colaborar'", 'verbose_name_plural': "'Como Colaborar'"},
        ),
        migrations.AlterModelOptions(
            name='quierodonar',
            options={'verbose_name': "'Quiero Donar'", 'verbose_name_plural': "'Quiero Donar'"},
        ),
    ]
