# Generated by Django 2.1.7 on 2019-04-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0014_auto_20190410_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorapp',
            name='imagen_sponsor',
        ),
        migrations.RemoveField(
            model_name='sponsorapp',
            name='page',
        ),
        migrations.RemoveField(
            model_name='sponsorapp',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='SponsorApp',
        ),
    ]
