# Generated by Django 2.1.7 on 2019-04-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190410_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='imagen_inferior_horizontal',
            new_name='imagen_inferior_kit',
        ),
        migrations.RenameField(
            model_name='carrera',
            old_name='imagen_inferior_vertical',
            new_name='imagen_inferior_mapa',
        ),
    ]
