# Generated by Django 2.1.7 on 2019-04-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_quierodonar_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='quierodonar',
            name='url_aumentar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quierodonar',
            name='url_donar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
