# Generated by Django 2.1.7 on 2019-04-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190411_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quierodonar',
            name='url_aumentar',
            field=models.URLField(blank=True, null=True, verbose_name='Url iframe aumento donacion '),
        ),
        migrations.AlterField(
            model_name='quierodonar',
            name='url_donar',
            field=models.URLField(blank=True, null=True, verbose_name='Url iframe donacion unica'),
        ),
    ]
