# Generated by Django 2.1.7 on 2019-04-11 02:39

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190411_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='alianzas',
            name='nota_pie',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
