# Generated by Django 2.1.7 on 2019-04-11 03:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0033_alianzas_nota_pie'),
    ]

    operations = [
        migrations.AddField(
            model_name='quehacemos',
            name='acciones_imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='acciones_texto',
            field=models.CharField(max_length=100, null=True, verbose_name='Acciones Texto'),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='banner_imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='comunitaria_imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='comunitaria_texto',
            field=models.CharField(max_length=100, null=True, verbose_name='Comunitaria Texto'),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='educacion_imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='educacion_texto',
            field=models.CharField(max_length=100, null=True, verbose_name='Educacion Texto'),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='imagen_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='trabajo_imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='trabajo_texto',
            field=models.CharField(max_length=100, null=True, verbose_name='Trabajo Texto'),
        ),
        migrations.AlterField(
            model_name='alianza',
            name='descripcion',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
