# Generated by Django 2.1.7 on 2019-04-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20190411_0507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={},
        ),
    ]
