# Generated by Django 2.1.7 on 2019-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_noticia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('CAT1', 'cat1'), ('CAT2', 'cat2'), ('CAT3', 'cat3'), ('CAT4', 'cat4')], default='CAT1', max_length=30),
        ),
    ]
