# Generated by Django 2.1.7 on 2019-04-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0044_auto_20190411_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen_portada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Educacion', 'Educacion'), ('Comunitaria', 'Comunitaria'), ('Pastorales', 'Pastorales'), ('Trabajo', 'Trabajo')], default='CAT1', max_length=30),
        ),
    ]
