# Generated by Django 2.1.7 on 2019-04-21 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='alianza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Alianzas',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('nota_pie', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('imagen_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': "'Alianzas'",
                'verbose_name': "'Alianzas'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('video_code', models.CharField(blank=True, max_length=70, null=True, verbose_name='Codigo Video')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AyudaDifundiendo',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('imagen_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': "'Ayuda Difundiendo'",
                'verbose_name': "'Ayuda Difundiendo'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('imagen_inferior_kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imagen_inferior_mapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imagen_superior_horizontal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imagen_superior_vertical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('politica_menores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('reglamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'verbose_name_plural': 'Home Carrera',
                'verbose_name': 'Home Carrera',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('inscripcion_url', models.URLField(verbose_name='Link de Incripcion')),
                ('distancia', models.CharField(max_length=10, verbose_name='Distancia')),
                ('valor', models.IntegerField(verbose_name='Valor de Inscripcion')),
                ('descripcion_categoria', models.CharField(max_length=30, verbose_name='Dificultad')),
            ],
            options={
                'verbose_name_plural': 'Carreras',
                'verbose_name': 'Carrera',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ComoColaborar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': "'Como Colaborar'",
                'verbose_name': "'Como Colaborar'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DondeEstamos',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('imagen_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': "'Donde Estamos'",
                'verbose_name': "'Donde Estamos'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': 'Home Pages',
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Legado',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('imagen_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': "'Ayuda Difundiendo'",
                'verbose_name': "'Ayuda Difundiendo'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('memoria_descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('memoria_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': "'Nosotros'",
                'verbose_name': "'Nosotros'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('categoria', models.CharField(choices=[('Educacion', 'Educacion'), ('Comunitaria', 'Comunitaria'), ('Pastorales', 'Pastorales'), ('Trabajo', 'Trabajo')], default='CAT1', max_length=30)),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('intro', models.CharField(max_length=250, verbose_name='Bajada')),
                ('body', wagtail.core.fields.RichTextField(blank=True, verbose_name='Cuerpo')),
                ('imagen_portada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'verbose_name': 'Noticia',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticiaGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.Noticia')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': 'Blog Noticias',
                'verbose_name': 'Blog Noticias',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QueHacemos',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('educacion_texto', models.CharField(max_length=400, null=True, verbose_name='Educacion Texto')),
                ('trabajo_texto', models.CharField(max_length=400, null=True, verbose_name='Trabajo Texto')),
                ('comunitaria_texto', models.CharField(max_length=400, null=True, verbose_name='Comunitaria Texto')),
                ('acciones_texto', models.CharField(max_length=400, null=True, verbose_name='Acciones Texto')),
                ('acciones_imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('banner_imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('comunitaria_imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('educacion_imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imagen_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('trabajo_imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': "'Que Hacemos'",
                'verbose_name': "'Que Hacemos'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('imagen_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': "'Quienes Somos'",
                'verbose_name': "'Quienes Somos'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QuieroDonar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('url_donar', models.URLField(blank=True, null=True, verbose_name='Url iframe donacion unica')),
                ('url_aumentar', models.URLField(blank=True, null=True, verbose_name='Url iframe aumento donacion ')),
                ('imagen_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': "'Quiero Donar'",
                'verbose_name': "'Quiero Donar'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SponsorClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nombre_sponsor', models.CharField(help_text='Overwrites the default title', max_length=100, verbose_name='Empresa')),
                ('url_sponsor', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Transparencia',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('imagen_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': "'Transparencia'",
                'verbose_name': "'Transparencia'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Video_Old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('video_code', models.CharField(blank=True, max_length=70, null=True, verbose_name='Codigo Video')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_videos_anteriores', to='home.Carrera')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SponsorApp',
            fields=[
                ('sponsorclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.SponsorClass')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_sponsor_app', to='home.App')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('home.sponsorclass',),
        ),
        migrations.CreateModel(
            name='SponsorCarrera',
            fields=[
                ('sponsorclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.SponsorClass')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_sponsor_carrera', to='home.Carrera')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('home.sponsorclass',),
        ),
        migrations.AddField(
            model_name='sponsorclass',
            name='imagen_sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='memoria',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoria_balance', to='home.Transparencia'),
        ),
        migrations.AddField(
            model_name='alianza',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='listado_alianzas', to='home.Alianzas'),
        ),
    ]
