# Generated by Django 2.1.7 on 2019-04-22 05:42

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190422_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegalleryimage',
            name='boton',
            field=models.BooleanField(default=False, verbose_name='Boton'),
        ),
        migrations.AddField(
            model_name='homegalleryimage',
            name='mesage',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Mensaje'),
        ),
        migrations.AddField(
            model_name='homegalleryimage',
            name='text_boton',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='homegalleryimage',
            name='url_boton',
            field=models.URLField(blank=True, verbose_name='Redireccionar a'),
        ),
    ]
