# Generated by Django 2.1.7 on 2019-04-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190422_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homegalleryimage',
            old_name='mesage',
            new_name='message',
        ),
    ]
