# Generated by Django 2.1.7 on 2019-04-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0006_noticia_noticiagalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': "'Nosotros'",
                'verbose_name': "'Nosotros'",
            },
            bases=('wagtailcore.page',),
        ),
    ]
