# Generated by Django 2.1.7 on 2019-04-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0007_nosotros'),
    ]

    operations = [
        migrations.CreateModel(
            name='DondeEstamos',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': "'DondeEstamos'",
                'verbose_name': "'DondeEstamos'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QueHacemos',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': "'Nosotros'",
                'verbose_name': "'Nosotros'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': "'Quienes Somos'",
                'verbose_name': "'Quienes Somos'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Transparencia',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name_plural': "'Transparencia'",
                'verbose_name': "'Transparencia'",
            },
            bases=('wagtailcore.page',),
        ),
    ]
