# Generated by Django 2.1.7 on 2019-04-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190410_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del video'),
        ),
    ]
