# Generated by Django 2.1.7 on 2019-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190410_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='video_code',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Codigo Video'),
        ),
    ]
