# Generated by Django 2.1.7 on 2019-04-10 15:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0013_carrera_video_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorApp',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('nombre_sponsor', models.CharField(help_text='Overwrites the default title', max_length=100, verbose_name='Empresa')),
                ('url_sponsor', models.URLField(blank=True, null=True)),
                ('imagen_sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_sponsor', to='home.App')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='imagen_sponsor',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
