# Generated by Django 2.1.7 on 2019-04-10 15:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0015_auto_20190410_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nombre_sponsor', models.CharField(help_text='Overwrites the default title', max_length=100, verbose_name='Empresa')),
                ('url_sponsor', models.URLField(blank=True, null=True)),
                ('imagen_sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='app',
            options={},
        ),
        migrations.AddField(
            model_name='sponsorapp',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_sponsor', to='home.App'),
        ),
    ]
