# Generated by Django 2.1.7 on 2019-04-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190410_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carrera'},
        ),
    ]
