# Generated by Django 2.1.7 on 2019-04-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0019_auto_20190410_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('inscripcion_url', models.URLField(verbose_name='Link de Incripcion')),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Distancia')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valor de Inscripcion')),
                ('descripcion_categoria', models.CharField(max_length=20, verbose_name='Dificultad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'Home Carrera', 'verbose_name_plural': 'Home Carrera'},
        ),
    ]
