# Generated by Django 2.1.7 on 2019-04-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190410_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='distancia',
            field=models.CharField(max_length=10, verbose_name='Distancia'),
        ),
        migrations.AlterField(
            model_name='carreras',
            name='valor',
            field=models.IntegerField(verbose_name='Valor de Inscripcion'),
        ),
    ]
