# Generated by Django 2.1.7 on 2019-04-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190410_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='descripcion_categoria',
            field=models.CharField(max_length=30, verbose_name='Dificultad'),
        ),
    ]
