# Generated by Django 2.1.7 on 2019-04-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0027_ayudadifundiendo_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='quierodonar',
            name='imagen_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
