# Generated by Django 2.1.7 on 2019-04-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190411_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quehacemos',
            name='acciones_texto',
            field=models.CharField(max_length=400, null=True, verbose_name='Acciones Texto'),
        ),
        migrations.AlterField(
            model_name='quehacemos',
            name='comunitaria_texto',
            field=models.CharField(max_length=400, null=True, verbose_name='Comunitaria Texto'),
        ),
        migrations.AlterField(
            model_name='quehacemos',
            name='educacion_texto',
            field=models.CharField(max_length=400, null=True, verbose_name='Educacion Texto'),
        ),
        migrations.AlterField(
            model_name='quehacemos',
            name='trabajo_texto',
            field=models.CharField(max_length=400, null=True, verbose_name='Trabajo Texto'),
        ),
    ]
