# Generated by Django 2.1.7 on 2019-04-11 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0038_memoria_memoria_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dondeestamos',
            options={'verbose_name': "'Quienes Somos'", 'verbose_name_plural': "'Quienes Somos'"},
        ),
        migrations.AddField(
            model_name='dondeestamos',
            name='imagen_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
