# Generated by Django 2.1.7 on 2019-04-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20190411_0545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'slider', 'verbose_name_plural': 'sliders'},
        ),
        migrations.AddField(
            model_name='slider',
            name='titles',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
