# Generated by Django 2.2.12 on 2020-04-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covid19',
            options={'verbose_name': 'Emergencia Covid', 'verbose_name_plural': "'Emergencia Covid'"},
        ),
    ]
