# Generated by Django 2.2.12 on 2020-04-21 14:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('institucion_nombre', models.CharField(max_length=60)),
                ('institucion_telefono', models.CharField(max_length=60)),
                ('institucion_direccion', models.CharField(max_length=255)),
                ('institucion_url', models.URLField(blank=True, null=True)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('descripcion', models.CharField(help_text='Acciones que se llevan a cabo', max_length=100, verbose_name='Descripcion')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='instituciones.Institucion')),
            ],
            options={
                'verbose_name': 'accion',
                'verbose_name_plural': 'acciones',
            },
        ),
    ]
