# Generated by Django 2.2.12 on 2020-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='institucion_nombre',
        ),
        migrations.AlterField(
            model_name='accion',
            name='descripcion',
            field=models.CharField(help_text='Acciones que se llevan a cabo', max_length=250, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='institucion_direccion',
            field=models.CharField(max_length=255, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='institucion_telefono',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='institucion_url',
            field=models.URLField(blank=True, null=True, verbose_name='WebPage'),
        ),
    ]
