# Generated by Django 2.2.12 on 2020-04-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0003_instituciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name': 'Institucion', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AddField(
            model_name='institucion',
            name='institucion_latlng',
            field=models.CharField(default='', max_length=255, verbose_name='LatLng'),
            preserve_default=False,
        ),
    ]
