# Generated by Django 2.2.12 on 2020-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0004_auto_20200422_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='institucion_latlng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LatLng'),
        ),
    ]
